products = [
    {
        "_id": "1",
        "name": "Pakiet 5 treningów",
        "image": "/images/dumbell.png",
        "description": "Pakiet 5 treningów personalnych z trenerem Grow Up",
        "brand": "Grow Up",
        "category": "Services",
        "price": 1200,
        "countInStock": 99999999999999999,
        "rating": 5,
        "numReviews": 12,
    },
    {
        "_id": "2",
        "name": "Pakiet 10 treningów",
        "image": "/images/dumbell.png",
        "description": "Pakiet 10 treningów personalnych z trenerem Grow Up",
        "brand": "Grow Up",
        "category": "Services",
        "price": 1600,
        "countInStock": 99999999999999999,
        "rating": 5,
        "numReviews": 85,
    },
    {
        "_id": "3",
        "name": "Pakiet 15 treningów",
        "image": "/images/dumbell.png",
        "description": "Pakiet 15 treningów personalnych z trenerem Grow Up",
        "brand": "Grow Up",
        "category": "Services",
        "price": 2000,
        "countInStock": 99999999999999999,
        "rating": 5,
        "numReviews": 85,
    },
    {
        "_id": "4",
        "name": "Pakiet 20 treningów",
        "image": "/images/dumbell.png",
        "description": "Pakiet 20 treningów personalnych z trenerem Grow Up",
        "brand": "Grow Up",
        "category": "Services",
        "price": 2300,
        "countInStock": 99999999999999999,
        "rating": 5,
        "numReviews": 85,
    },
    {
        "_id": "5",
        "name": "Kurs trenera personalnego",
        "image": "/images/academy.png",
        "description": "Profesjonalny kurs trenera personalnego prowadzny przez doświadczonych trenerów Grow Up.",
        "brand": "Grow Up",
        "category": "Services",
        "price": 4000,
        "countInStock": 11,
        "rating": 5,
        "numReviews": 12,
    },
    
]
