export const TRAINER_LIST_REQUEST = "TRAINER_LIST_REQUEST";
export const TRAINER_LIST_SUCCESS = "TRAINER_LIST_SUCCESS";
export const TRAINER_LIST_FAIL = "TRAINER_LIST_FAIL";

export const BOOK_TRAINING_SESSION_REQUEST = 'BOOK_TRAINING_SESSION_REQUEST';
export const BOOK_TRAINING_SESSION_SUCCESS = 'BOOK_TRAINING_SESSION_SUCCESS';
export const BOOK_TRAINING_SESSION_FAIL = 'BOOK_TRAINING_SESSION_FAIL';

export const TRAINER_LIST_REQUEST = "TRAINER_LIST_REQUEST";
export const TRAINER_LIST_SUCCESS = "TRAINER_LIST_SUCCESS";
export const TRAINER_LIST_FAIL = "TRAINER_LIST_FAIL";