export const TRAINER_LIST_REQUEST = "TRAINER_LIST_REQUEST";
export const TRAINER_LIST_SUCCESS = "TRAINER_LIST_SUCCESS";
export const TRAINER_LIST_FAIL = "TRAINER_LIST_FAIL";

export const BOOK_TRAINING_SESSION_REQUEST = 'BOOK_TRAINING_SESSION_REQUEST';
export const BOOK_TRAINING_SESSION_SUCCESS = 'BOOK_TRAINING_SESSION_SUCCESS';
export const BOOK_TRAINING_SESSION_FAIL = 'BOOK_TRAINING_SESSION_FAIL';

export const SESSION_LIST_REQUEST = "SESSION_LIST_REQUEST";
export const SESSION_LIST_SUCCESS = "SESSION_LIST_SUCCESS";
export const SESSION_LIST_FAIL = "SESSION_LIST_FAIL";

export const _DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";