# Generated by Django 5.0.1 on 2024-03-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='is_paid',
        ),
    ]
